### ISSUE TITLE
plot_field.py coordinate math

### ISSUE THREAD

**Issue by tikk3r** [LOFAR-VLBI/lofar-vlbi-pipeline#2]
I think there may be an issue in how `plot_field.py` calculates distances for the plot. Running it for this high-dec field at +74 on a target that is ~1.21 deg away from the pointing centre according to the LTA, it produces this:
![output_old](https://github.com/user-attachments/assets/94e75aba-b4b8-4503-af82-facd884a1bca)

Going from 4.36 to 1.21 is approximately the cos(dec) factor. Switching to `SkyCoord.separation` instead of the linear difference in RA and DEC, and using astropy's `SphericalCircle` to plot I get this which seems to agree more with the LoTSS HiPS:
![output](https://github.com/user-attachments/assets/68ea6f78-8d0c-430c-86f9-ce66e1ef7c9d)

**Comment by jwpetley** [comment]
This should be fixed in 4a9813f . Thank you for finding where the quick maths falls apart. 

The distances in the catalogue creation were always accurate in case those reading this issue were concerned!
